### ISSUE TITLE
Local directory is visible in archive

### ISSUE THREAD

**Issue by zaps166** [mate-desktop/engrampa#120]
Engrampa (1.12.0, Manjaro/Arch Linux) shows local directory inside archive, e.g. for "wordpress-4.4.1-pl_PL.zip" i can see:
- wordpress - OK,
- home - Not OK.

Why "home" directory is inside "wordpress-4.4.1-pl_PL.zip" (of course it doesn't exist in archive) ? :D Full path: "home/username/Desktop/wordpress-4.4.1-pl_PL.zip" - this is the only visible file.

I can also see "tmp" directory inside (it depends on which folder the archive is located).

From "mount":
```
tmpfs on /tmp type tmpfs (rw)
/dev/sda2 on /home type ext4 (rw,relatime,data=ordered)
```
![przechwycenie obrazu ekranu_2016-01-24_03-06-40](https://cloud.githubusercontent.com/assets/6239090/12534029/7f7397de-c247-11e5-860c-8fdb0c72cf44.png)

**Comment by raveit65** [comment]
This is already fixed by our side.
Please ask yor distro maintainer to backport the fix from master branch.
https://github.com/mate-desktop/engrampa/commit/4f65bde8fc4d4efe747d4e7fbeba1211469ed79a
Ps: you can avoid the huusle to file out here a report if you first file out a report against you distro next time.
Thank you

**Comment by zaps166** [comment]
Thanks! I've seen the commit 4f65bde8fc4d4efe747d4e7fbeba1211469ed79a, but I didn't realize that correct checking for 7z version can fix this problem! Next time I'll compile and try GIT version first!
