### ISSUE TITLE
is it possible to not (hard) depend on caja?

### ISSUE THREAD

**Issue by kn00tcn** [mate-desktop/engrampa#208]
i am wondering how viable it is to make engrampa more standalone or if most of its usage can work with a dummy caja package on the OS (i got stuck trying to figure out how to make dummy packages so i cant try this yet)

**Comment by lukefromdc** [comment]
To do this, the caja-engrampa portion of the source package would have to be switched from building unconditionally (thus requiring caja which is checked for in configure.ac) to being built only if caja's presence on the build system is detected and perhaps a --disable-caja switch is not passed at ./autogen.sh.

The problem would be this: if a distro wants to built Engrampa for mate (with menuentry in Caja's right click menu to compress a file or files), the build would have to be with caja enabled. To also offer a version of Engrampa that does not depend on Caja would be a second build from the same source with --disable-caja(or whatever flag was used) passed.

The only war around that would be a "lazy loading" like in Firefox where a module is loaded only when it is both present and is being used, so that the caja extension would load only if Caja is present on the system.

**Comment by lukefromdc** [comment]
Engrampa installs libcaja-engrampa.so, but the function of that library is to allow caja to call Engrampa, not the other way around. If you load engrampa from terminal with caja not installed (after force-install, make-install followed by caja removal, dummy package, etc) and don't get error messages, that means we have caja as a buildtime dependency but not a runtime dependency, and that another /usr/share/caja/extensions/libcaja-engrampa.caja-extension tells caja to load libcaja-engrampa.so. The result is Caja can certainly be installed without Engrampa, and you just found a normal build of Engrampa can also run without caja present. 

Thus, it should be possible for distros to move Caja to "recommends" instead of "depends" for Engrampa if nobody else finds a problem

**Comment by kn00tcn** [comment]
does upstream (aka here) decide on deps or do distro maintainers decide based on their testing or recommendations by upstream?

i noticed in one distro, vlc requires samba while in another it's optional

**Comment by zhuyaliang** [comment]
Use ```--disable-caja-actions``` to not rely on ```libcaja-extension```
