### ISSUE TITLE
Question / Request concerning iso support

### ISSUE THREAD

**Issue by rcaridade145** [mate-desktop/engrampa#214]
Is adding a dependency on https://cdemu.sourceforge.io/about/libmirage/ a possibility? 
There is a simple implementation here https://github.com/richardgv/isoextract .

Thank you for Mate

**Comment by rcaridade145** [comment]
Mainly support for many more formats of iso images. @vkareh

**Comment by kn00tcn** [comment]
iso is a specific image format, you mean you just want more image formats supported

i've run into libmirage's page before, looks promising, dont know how feasible it is

isoextract has the problem of being abandoned, doesnt even support UDF, but that's weird since it's supposed to depend on libmirage

in the meantime, just mount the images for use in file managers

**Comment by zhuyaliang** [comment]
It seems that [libmirage](https://koji.fedoraproject.org/koji/packageinfo?packageID=6757) is no longer maintained on Fedora, so I need to close this issue
