### ISSUE TITLE
Option to always extract to sub folder.

### ISSUE THREAD

**Issue by Ryder17z** [mate-desktop/engrampa#449]
#### Expected behaviour
A setting that makes every archive extract into PATH/archive_name/

#### Actual behaviour
Can't even on-demand request the application to extract into a subdir, populating the directory name automatically.

#### Steps to reproduce the behaviour
Extract any archive.

#### MATE general version
N/A

#### Package version
Engrampa 1.26.0

#### Linux Distribution
Manjaro XFCE

#### Link to bugreport of your Distribution (requirement)
N/A

#### Why do I want this?
Many archives are a flat structure, dumping their contents directly into the Downloads folder is far from ideal.
If it could automatically extract into sub folders it is much easier to have things organized.

**Comment by zhuyaliang** [comment]
@Ryder17z Can you explain the operation steps in detail

**Comment by Ryder17z** [comment]
How is it not clear enough?

Any competent tool even back when windows 9x was commonplace could easily extract archives into separate folders (implementations may differ between softwares) but they all had some way to do it.

**Comment by xmusjackson** [comment]
@Ryder17z I don't think the hostility is necessary at all. You're giving a suggestion that someone do work for you for free, operation details don't seem like much to ask.

@zhuyaliang The option would allow for a directory to be created with the name of the archive and the contents of the archive to be extracted there. Example:
1. Archive named "HBInvent.zip" is selected in the open dialog
2. A directory is selected in the extract dialog (such as /home/<username>)
3. A checkbox is enabled in the extract dialog (named something like "Extract to subdirectory")
4. If necessary, the user is prompted to allow the creation of a directory with the name of the archive in the selected directory
  Example: /home/<username>/HBInvent
5. The contents of the archive are extracted to this new directory instead of the selected directory

I've created a basic implementation of the function. I tried to stick with the standards as best I could but I haven't gone over the entire program and I'm new to gtk and glib. This implementation adds a new key to the GSettings DB as well, allowing for the setting to be kept. This works well on my end but has not been tested substantially.

It's here, if interested: https://github.com/xmusjackson/engrampa/commit/81c4f36e9a188a34ed8531622adf3dbfeb4cd723

**Comment by zhuyaliang** [comment]
@xmusjackson Thank you for your work. Can you initiate this PR? I would be happy to review the code

**Comment by Ryder17z** [comment]
@xmusjackson there's a difference between hostility and rudeness. The latter I can agree to. It was just really frustrating as I hadn't found a better archive tool.

Out of curiosity, I skimmed your implementation and I got no complaints, but I also don't know what is the best way to implement this.
